language: python

python:
  - "2.7"

virtualenv:
  system_site_packages: true

before_install:
  - sudo apt-get update

install:
  - if [[ $TRAVIS_PYTHON_VERSION == 2.7 ]]; then
      sudo apt-get install --fix-missing python-opencv python-numpy python-zbar libdmtx-dev
      pip install -e 'git+git://libdmtx.git.sourceforge.net/gitroot/libdmtx/dmtx-wrappers#egg=pydmtx&subdirectory=python';
    fi
  - pip install -r requirements.txt
  - "export DISPLAY=:99.0"
  - "sh -e /etc/init.d/xvfb start"

script:
- nosetests

