language:
  - python

sudo:
  - required

python:
  - "2.7"

virtualenv:
  system_site_packages: true

install:
  - sudo apt-get -qq update
  - sudo apt-get install -y --fix-missing libdmtx0a libzbar0 python-opencv
  - pip install -r requirements.pip

script:
  - nosetests

after_success:
  - coveralls
